import {
	Banknote,
	BriefcaseBusiness,
	Lightbulb,
	UsersRound,
} from "lucide-react";

export const rootNavLinks = [
	{
		slug: "/about",
		label: "About",
	},
	{
		slug: "/blogs",
		label: "Blogs",
	},
	{
		slug: "/faqs",
		label: "FAQs",
	},
	{
		slug: "/contact",
		label: "Contact us",
	},
];

export const footer = [
	{
		title: "Earnsphere",
		links: [
			{
				slug: "/register",
				label: "Get started",
			},
			{
				slug: "/pricing",
				label: "Pricing",
			},
			{
				slug: "/help-center",
				label: "Help center",
			},
		],
	},
	{
		title: "Company",
		links: [
			{
				slug: "/about",
				label: "About us",
			},
			{
				slug: "/blog",
				label: "Blog",
			},
			{
				slug: "/faqs",
				label: "FAQs",
			},
			{
				slug: "/contact",
				label: "Contact us",
			},
		],
	},
	{
		title: "Social media",
		links: [
			{
				slug: "www.youtube.com",
				label: "Youtube",
			},
			{
				slug: "www.facebook.com",
				label: "Facebook",
			},
			{
				slug: "www.instagram.com",
				label: "Instagram",
			},
			{
				slug: "www.x.com",
				label: "X",
			},
		],
	},
	{
		title: "Legal",
		links: [
			{
				slug: "/terms-of-use",
				label: "Terms of use",
			},
			{
				slug: "/privacy-policy",
				label: "Privacy policy",
			},
			{
				slug: "/cookies",
				label: "Cookies",
			},
			{
				slug: "/affiliate-agreement",
				label: "Affiliate agreement",
			},
			{
				slug: "/partner-agreement",
				label: "Partner agreement",
			},
		],
	},
];

export const howDetails = [
	{
		icon: BriefcaseBusiness,
		title: "Verified Micro-Jobs & Campaigns",
		subTitle:
			"Earn effortlessly by completing simple tasks from verified brands and businesses.",
		description:
			"From engaging with content to reviewing products, every task is beginner-friendly, guided, and pays instantly upon verification. Whether you have 5 minutes or 1 hour, there’s always something you can do to earn real money.",
	},
	{
		icon: Banknote,
		title: "Up to 15% Cashback",
		subTitle:
			"Get rewarded while you shop with exclusive cashback deals from partnered brands.",
		description:
			"Browse through our growing list of partner stores, make purchases through your unique links, and enjoy cashback rewards — up to 15% back on what you spend. Stack savings and turn everyday spending into earning!",
	},
	{
		icon: Lightbulb,
		title: "Learn & Level Up",
		subTitle:
			"Grow your skills while earning with our on-platform learning hub.",
		description:
			"Access bite-sized courses and resources on affiliate marketing, content strategy, digital growth, and social media. Whether you're just starting or looking to grow, you’ll find tools to help you earn smarter.",
	},
	{
		icon: UsersRound,
		title: "Trusted Community",
		subTitle: "Join a vibrant network of digital earners and achievers.",
		description:
			"Connect with others through forums, climb the leaderboard, and unlock champion rewards as you complete tasks. Our platform celebrates your progress, so every effort moves you forward in the community.",
	},
];

export const EMAIL_ADDRESS = "contact@earnsphere.com";
export const PHONE_NUMBER = "+234 800 233 4433";
export const YOUTUBE_URL = "www.youtube.com";
export const INSTAGRAM_URL = "www.instagram.com";
export const FACEBOOK_URL = "www.facebook.com";
export const X_URL = "www.x.com";

export const subjects = [
	"General enquiry",
	"Technical support",
	"Payment support",
];

export const countries = [
	"Afghanistan",
	"Albania",
	"Algeria",
	"Andorra",
	"Angola",
	"Antigua and Barbuda",
	"Argentina",
	"Armenia",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahamas",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bhutan",
	"Bolivia",
	"Bosnia and Herzegovina",
	"Botswana",
	"Brazil",
	"Brunei",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Cabo Verde",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Central African Republic",
	"Chad",
	"Chile",
	"China",
	"Colombia",
	"Comoros",
	"Congo (Congo-Brazzaville)",
	"Costa Rica",
	"Croatia",
	"Cuba",
	"Cyprus",
	"Czech Republic",
	"Democratic Republic of the Congo",
	"Denmark",
	"Djibouti",
	"Dominica",
	"Dominican Republic",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Equatorial Guinea",
	"Eritrea",
	"Estonia",
	"Eswatini",
	"Ethiopia",
	"Fiji",
	"Finland",
	"France",
	"Gabon",
	"Gambia",
	"Georgia",
	"Germany",
	"Ghana",
	"Greece",
	"Grenada",
	"Guatemala",
	"Guinea",
	"Guinea-Bissau",
	"Guyana",
	"Haiti",
	"Honduras",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran",
	"Iraq",
	"Ireland",
	"Israel",
	"Italy",
	"Ivory Coast",
	"Jamaica",
	"Japan",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kiribati",
	"Kuwait",
	"Kyrgyzstan",
	"Laos",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshall Islands",
	"Mauritania",
	"Mauritius",
	"Mexico",
	"Micronesia",
	"Moldova",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Morocco",
	"Mozambique",
	"Myanmar (Burma)",
	"Namibia",
	"Nauru",
	"Nepal",
	"Netherlands",
	"New Zealand",
	"Nicaragua",
	"Niger",
	"Nigeria",
	"North Korea",
	"North Macedonia",
	"Norway",
	"Oman",
	"Pakistan",
	"Palau",
	"Palestine",
	"Panama",
	"Papua New Guinea",
	"Paraguay",
	"Peru",
	"Philippines",
	"Poland",
	"Portugal",
	"Qatar",
	"Romania",
	"Russia",
	"Rwanda",
	"Saint Kitts and Nevis",
	"Saint Lucia",
	"Saint Vincent and the Grenadines",
	"Samoa",
	"San Marino",
	"Sao Tome and Principe",
	"Saudi Arabia",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"South Korea",
	"South Sudan",
	"Spain",
	"Sri Lanka",
	"Sudan",
	"Suriname",
	"Sweden",
	"Switzerland",
	"Syria",
	"Taiwan",
	"Tajikistan",
	"Tanzania",
	"Thailand",
	"Timor-Leste",
	"Togo",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkey",
	"Turkmenistan",
	"Tuvalu",
	"Uganda",
	"Ukraine",
	"United Arab Emirates",
	"United Kingdom",
	"United States of America",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Vatican City",
	"Venezuela",
	"Vietnam",
	"Yemen",
	"Zambia",
	"Zimbabwe",
];

export const banks = [
	"Access Bank",
	"Citibank Nigeria",
	"Ecobank Nigeria",
	"Fidelity Bank",
	"First Bank of Nigeria",
	"First City Monument Bank (FCMB)",
	"Globus Bank",
	"Guaranty Trust Bank (GTBank)",
	"Heritage Bank",
	"Keystone Bank",
	"Polaris Bank",
	"Providus Bank",
	"Stanbic IBTC Bank",
	"Standard Chartered Bank",
	"Sterling Bank",
	"SunTrust Bank",
	"Titan Trust Bank",
	"Union Bank of Nigeria",
	"United Bank for Africa (UBA)",
	"Unity Bank",
	"Wema Bank",
	"Zenith Bank",
];

export const DEFAULT_PROFILE_PICTURE =
	"https://icon-library.com/images/anonymous-avatar-icon/anonymous-avatar-icon-25.jpg";

export const identificationTypes = ["NIN", "BVN"];
